name: ci
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [26]
        elixir: ["1.16"]
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
      - uses: actions/cache@v4
        id: mix-cache # id to use in retrieve action
        with:
          path: |
            _build
            deps
          key: test-cache-v0-${{matrix.elixir}}-${{matrix.otp}}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - if: steps.mix-cache.outputs.cache-hit != 'true'
        run: mix do deps.get, deps.compile
      - run: make lint
      - run: mix test