on: push

jobs:
  test:
    # services:
    #     # Label used to access the service container
    #     postgres:
    #       # Docker Hub image
    #       image: postgres
    #       # Provide the password for postgres
    #       env:
    #         POSTGRES_PASSWORD: postgres
    #       # Set health checks to wait until postgres has started
    #       options: >-
    #         --health-cmd pg_isready
    #         --health-interval 10s
    #         --health-timeout 5s
    #         --health-retries 5
    #       ports:
    #         # Maps tcp port 5432 on service container to the host
    #         - 5432:5432

    runs-on: ubuntu-latest
    name: Elixir
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26.2.3
          elixir-version: 1.16.2
      # - run: make setup
      - run: make lint
      - run: make test