name: ci
on: push

env:
  ERLANG_VERSION: "26"
  ELIXIR_VERSION: "1.16"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{env.ELIXIR_VERSION}}
          otp-version: ${{env.ERLANG_VERSION}}
      - uses: actions/cache@v4
        id: mix-cache # id to use in retrieve action
        with:
          path: |
            _build
            deps
          key: test-cache-v0-${{env.ELIXIR_VERSION}}-${{env.ERLANG_VERSION}}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - if: steps.mix-cache.outputs.cache-hit != 'true'
        run: make build
      - run: make test
      - run: make lint